server {
    listen 8080;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # SPA (React) 라우팅을 위해 fallback 설정
        try_files $uri $uri/ /index.html;
    }
}
